/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: "class",
  content: [
    "./app/**/*.{js,ts,jsx,tsx,mdx}",
    "./components/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        "on-surface": "#2f3334",
        primary: "#5e5f61",
        "tertiary-fixed-dim": "#a8d9ee",
        "on-tertiary": "#f2faff",
        "on-primary-container": "#505254",
        "inverse-primary": "#f9f9fc",
        "secondary-fixed": "#bfece3",
        outline: "#777b7c",
        "on-primary": "#f9f9fb",
        background: "#f9f9f9",
        "on-background": "#2f3334",
        "on-secondary-fixed-variant": "#39635c",
        "on-primary-fixed": "#3e3f42",
        surface: "#f9f9f9",
        "secondary-dim": "#305a54",
        "tertiary-fixed": "#b5e7fd",
        secondary: "#3d6660",
        "tertiary-container": "#b5e7fd",
        "outline-variant": "#aeb3b3",
        "secondary-container": "#bfece3",
        "primary-fixed-dim": "#d4d4d7",
        "surface-container-low": "#f2f4f4",
        "error-dim": "#67040d",
        "on-error": "#fff7f6",
        "on-tertiary-fixed": "#064355",
        "on-secondary-container": "#2f5953",
        "secondary-fixed-dim": "#b1ddd5",
        "surface-variant": "#dfe3e4",
        "on-error-container": "#6e0a12",
        "surface-container-high": "#e6e9e9",
        "inverse-surface": "#0c0f0f",
        "inverse-on-surface": "#9c9d9d",
        "error-container": "#fa746f",
        "surface-bright": "#f9f9f9",
        "primary-container": "#e2e2e5",
        "surface-container-lowest": "#ffffff",
        tertiary: "#336578",
        "tertiary-dim": "#26596b",
        "on-secondary": "#e2fff9",
        "surface-container-highest": "#dfe3e4",
        "on-primary-fixed-variant": "#5a5c5e",
        "on-secondary-fixed": "#1b4640",
        "primary-dim": "#525355",
        "on-tertiary-fixed-variant": "#2e6072",
        "primary-fixed": "#e2e2e5",
        "surface-tint": "#5e5f61",
        "on-tertiary-container": "#225668",
        "surface-container": "#eceeef",
        "on-surface-variant": "#5b6061",
        error: "#a83836",
        "surface-dim": "#d7dbdb",
      },
      borderRadius: {
        DEFAULT: "1rem",
        lg: "2rem",
        xl: "3rem",
        full: "9999px",
      },
      fontFamily: {
        headline: ["var(--font-plus-jakarta-sans)", "sans-serif"],
        body: ["var(--font-manrope)", "sans-serif"],
        label: ["var(--font-manrope)", "sans-serif"],
      },
    },
  },
  plugins: [require("@tailwindcss/forms")],
};
